### ISSUE TITLE
RuntimeError: torch._scaled_mm is only supported on devices with compute capability >= 9.0)

### ISSUE THREAD

**Issue by vgoklani** [pytorch-labs/float8_experimental#197]
Possible to add support for the NVIDIA Ada Lovelace cards, which have a compute capability of 8.9?

NVIDIA's TransformerEngine works, so the feature is supported in the hardware.

Thanks!

**Comment by drisspg** [comment]
Would you mind creating an issue on the main PyTorch repo and tagging me?

**Comment by vgoklani** [comment]
Done

https://github.com/pytorch/pytorch/issues/118703

**Comment by drisspg** [comment]
PR should land in nightly by tomorrow :)

**Comment by vgoklani** [comment]
Thank you @drisspg
