### ISSUE TITLE
Float8 + Per-Parameter FSDP

### ISSUE THREAD

**Issue by drisspg** [pytorch-labs/float8_experimental#201]
We will investigate fp8 all-gather for both dynamic and delayed scaling. Throughout, "fp8 all-gather" refers to moving casts to fp8 to _before_ all-gather specifically for `Float8Linear.weight`/`Float8DynamicLinear.weight`. Other parameters are all-gathered with dtype according to FSDP's mixed precision policy.

## Per-parameter FSDP with dynamic scaling
- fp8 all-gather may not be justified due to requiring all-reducing the amax (across data parallel workers) before computing scales.
    - Batching these all-reduces into one in eager requires some extra API and internals change, where the amax could not be computed inline but rather externally for many weights at once, e.g. after the optimizer step.
    - With respect to communication time, no batching could nullify the savings from fp8 all-gather in a latency-bound regime and only be helpful in a bandwidth-bound regime.
- Dynamic scaling in eager has too much CPU overhead. Compiling seems like a requirement.
    - Without fp8 all-gather, we can already compile the dynamic scaling since it is part of the module forward, similar to existing FSDP.
    - With fp8 all-gather, we have issues tracing the `Float8DynamicLinearWeightTensor` subclass added to run the fp8 all-gather: P1182470218.
- fp8 all-gather with bf16 mixed precision has different numerics than bf16 all-gather because the amax/scale is computed from the fp32 sharded parameter for the fp8 all-gather but from the bf16 unsharded parameter for the bf16 all-gather.
- On having the `Float8DynamicLinear.weight` be a tensor subclass:
    - This was to define `fsdp_pre_all_gather()` and `fsdp_post_all_gather()` methods to customize the all-gather.
    - We have to pass `foreach=True` to the optimizer to use foreach path.
    - The `Float8Tensor._data` is now of type `Float8DynamicLinearWeightTensor`. For now, this means calls (e.g. `numel()`/`view()`), go through `__torch_function__`, which adds overhead.
    - To-do: We need to make this compile-friendly and see how to save state on the tensor that can be propagated. For the latter, we currently pass `module` to `fsdp_pre_all_gather()` as a way for the method to read state.

## Per-parameter FSDP with delayed scaling
Not yet started

**Comment by awgu** [comment]
## Per-parameter FSDP with dynamic scaling
- Should we all-reduce the amax before computing the scale?
- If using FSDP's bf16 mixed precision, using fp8 all-gather vs. not gives different numerics.
    - If using fp8 all-gather, then the amax and scales are computed with respect to the fp32 sharded parameter.
    - If not using fp8 all-gather, then the amax and scales are computed with respect to the bf16 unsharded parameter.
    - The former should be preferred, but the difference makes unit testing the fp8 all-gather challenging.
- On having the `Float8DynamicLinear.weight` be a tensor subclass:
    - Why? We want to add two methods `fsdp_pre_all_gather()` and `fsdp_post_all_gather()`.
    - Because it is a subclass, the optimizer falls back to the single-tensor (non-`foreach` path) unless the user passes `foreach=True`.
    - To-do: I need to figure out how to save state (e.g. `module.emulate`) on the subclass and propagate it through ops. To work around for now, I pass `module` into the `fsdp_pre_all_gather()`, so the subclass can read the state off the module. After this, we need to look at the performance implication of having the weight be a subclass (mainly CPU overhead).

**Comment by vkuzo** [comment]
closing as this works now
