### ISSUE TITLE
swap_linear_with_float8_linear does not swap torch.nn.Linear if it's the model itself

### ISSUE THREAD

**Issue by yitzhaklevi** [pytorch-labs/float8_experimental#206]
`
# this would do nothing
model1 = torch.nn.Linear([16, 16])
swap_linear_with_float8_linear(model1, Float8Linear)

# this would work
model2 = torch.nn.Sequential(torch.nn.Linear([16, 16]))
swap_linear_with_float8_linear(model2, Float8Linear)
`
the reason is due to the fact that model1 has no child modules, 
(the use case is quite odd, but it would be useful to change the function signature since it's not working as expected)

**Comment by awgu** [comment]
https://github.com/pytorch-labs/float8_experimental/pull/208
