### ISSUE TITLE
FP8 only requires compute capability 8.9

### ISSUE THREAD

**Issue by mabeto5p** [pytorch-labs/float8_experimental#236]
According to the cuBlas docs the compute capability required for fp8 is only 8.9, but scaled_mm checks for compute capability larger than 9.0, am I missing something? 

See section 5.1.4 here https://docs.nvidia.com/cuda/pdf/CUBLAS_Library.pdf

**Comment by drisspg** [comment]
Is this a duplicxate of : https://github.com/pytorch-labs/float8_experimental/issues/197?

**Comment by mabeto5p** [comment]
Yes, sorry :)

**Comment by drisspg** [comment]
No worries, if you are getting some value on sm89 please feel free to share I would be curious about the overall perf on consumer cards
