### ISSUE TITLE
Any quality benchmarks?

### ISSUE THREAD

**Issue by tsengalb99** [pytorch-labs/float8_experimental#318]
Do you have any benchmarks measuring degradation from using fp8 vs bf16 mixed precision?

**Comment by vkuzo** [comment]
hi @tsengalb99 , I think this is the best list of accuracy benchmarks from float8: https://github.com/NVIDIA/TransformerEngine?tab=readme-ov-file#fp8-convergence .  This repo is doing the same thing mathematically as TransformerEngine.

we also just moved the code to https://github.com/pytorch/ao/tree/main/torchao/float8, so please feel free to continue the discussion there!
