### ISSUE TITLE
[Perf] Explore more performant Fp8 Casting

### ISSUE THREAD

**Issue by drisspg** [pytorch-labs/float8_experimental#83]
# Summary
There are two components to this, non_saturated casting and saturated casting.

### Non-Saturated casting
- We are currently using bit logic to cast from fp32 to fp8 where as there exists intrinsics to perform the same, see Nikitas comment below.
- Currently for fp16 -> fp8 casting we actually first rescaled fp16 to fp32 and then recast to fp8.

### Saturated Casting
- In this codebase we write out the saturated cast logic explicitly by clamping prior to conversion: https://github.com/pytorch-labs/float8_experimental/blob/cdcadb57c5f4736d1a78a794da98afd398571942/float8_experimental/float8_utils.py#L19
There does appear to be intrinisics with PTX for doing saturated casts, see: https://github.com/openai/triton/blob/10f59d8ce04052521c1bc0cb3a3f8b98918fc7e3/lib/Conversion/TritonGPUToLLVM/ElementwiseOpToLLVM.cpp#L182

**Comment by drisspg** [comment]
I further explored this and created a kernel cuda as well to do the casting here:
https://github.com/drisspg/driss_torch/blob/1a8c41c84c9521f35a7f9332da08813ea20608b1/driss_torch/__init__.py#L30

Performance comparing against inductor/triton can be found here: 
https://github.com/drisspg/driss_torch/commit/67c596eed43d8ffb670cc96f3741c45c20225f19

Note though is that I also need to add an option to return the matrix in transposed format ( which we will need to fuse for the backward).

For delayed scaling we would expect the absmax calc to be fused into the prior op, and then this fused kernel could be used based off of the historical scale. We should weigh though if it is worth the added complexity to ship in this repo

**Comment by vkuzo** [comment]
moved to https://github.com/pytorch/ao/issues/559
